### ISSUE TITLE
CSS file

### ISSUE THREAD

**Issue by Bobur-kobilov** [PacktPublishing/Vue.js-2.x-by-Example#1]
How can I find CSS files for codes? Thank you for the book!

**Comment by mikestreety** [comment]
Hi @Bobur-kobilov!

Thanks for the feedback. There isn't really any CSS included with the book/code is it focusses on Vue and tried to be style agnostic (I didn't want to include loads of bootstrap html classes, for example) so you can use it with the CSS you have.

For later on in the book (spoiler alert 😉) I use [tacit.css](http://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-css-1.1.0.min.css) which gives basic styling to elements.

Hope that helps!

Mike
